# Generated by Django 3.0.4 on 2022-07-25 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0026_auto_20220715_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='accomplishments',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
